-- Generated by the Organizer Library (03/07/16 17:11:26)
return {
    [1]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="chatoyant staff", 
        ["id"]=18633, 
        ["name"]="chatoyant staff", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="fili hongreline", 
        ["id"]=26916, 
        ["name"]="fili hongreline", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="brioso roundlet", 
        ["id"]=27672, 
        ["name"]="brioso roundlet", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="steelflash earring", 
        ["id"]=28520, 
        ["name"]="steelflash earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="fili cothurnes", 
        ["id"]=27429, 
        ["name"]="fili cothurnes", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="bladeborn earring", 
        ["id"]=28521, 
        ["name"]="bladeborn earring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="bihu cannions +1", 
        ["id"]=27171, 
        ["name"]="bihu cannions +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="brioso cuffs", 
        ["id"]=27952, 
        ["name"]="brioso cuffs", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="atheling mantle", 
        ["id"]=16260, 
        ["name"]="atheling mantle", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="swith cape", 
        ["id"]=11000, 
        ["name"]="swith cape", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="fili rhingrave", 
        ["id"]=27255, 
        ["name"]="fili rhingrave", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="asperity necklace", 
        ["id"]=28402, 
        ["name"]="asperity necklace", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="brioso slippers", 
        ["id"]=28232, 
        ["name"]="brioso slippers", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="phasmida belt", 
        ["id"]=10815, 
        ["name"]="phasmida belt", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="fili calot", 
        ["id"]=26758, 
        ["name"]="fili calot", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="suppanomimi", 
        ["id"]=14739, 
        ["name"]="suppanomimi", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="rhapsode's cape", 
        ["id"]=28626, 
        ["name"]="rhapsode's cape", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="porous rope", 
        ["id"]=28409, 
        ["name"]="porous rope", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="kali", 
        ["id"]=20599, 
        ["name"]="kali", 
        ["count"]=1
    }
}