-- Generated by the Organizer Library (02/15/16 21:14:59)
return {
    [1]={
        ["log_name"]="icesoul ring", 
        ["id"]=11657, 
        ["name"]="icesoul ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="icesoul ring", 
        ["id"]=11657, 
        ["name"]="icesoul ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="hecate's earring", 
        ["id"]=11698, 
        ["name"]="hecate's earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="swith cape", 
        ["id"]=11000, 
        ["name"]="swith cape", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="summoner's spats", 
        ["id"]=15131, 
        ["name"]="summoner's spats", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="apogee crown", 
        ["id"]=26676, 
        ["name"]="apogee crown", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="shiva ring", 
        ["id"]=27574, 
        ["name"]="shiva ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="shiva ring", 
        ["id"]=27574, 
        ["name"]="shiva ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="conveyance cape", 
        ["id"]=28631, 
        ["name"]="conveyance cape", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Mag. Acc.+24 \"Mag.Atk.Bns.\"+24", 
            [2]="Magic burst mdg.+5%", 
            [3]="Mag. Acc.+14", 
            [4]="\"Mag.Atk.Bns.\"+8"
        }
    }, 
    [13]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Mag. Acc.+28", 
            [2]="\"Fast Cast\"+6", 
            [3]="INT+6"
        }
    }, 
    [14]={
        ["log_name"]="gyve trousers", 
        ["id"]=27324, 
        ["name"]="gyve trousers", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="merlinic dastanas", 
        ["id"]=27141, 
        ["name"]="merlinic dastanas", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="leviathan ring", 
        ["id"]=27566, 
        ["name"]="levia. ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="leviathan ring", 
        ["id"]=27566, 
        ["name"]="levia. ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="asperity necklace", 
        ["id"]=28402, 
        ["name"]="asperity necklace", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="marduk's jubbah +1", 
        ["id"]=27791, 
        ["name"]="marduk's jubbah +1", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="nirvana", 
        ["id"]=21141, 
        ["name"]="nirvana", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Pet: Accuracy+29 Pet: Rng. Acc.+29", 
            [2]="\"Avatar perpetuation cost\" -2", 
            [3]="System: 1 ID: 1792 Val: 7", 
            [4]="Pet: Mag. Acc.+3", 
            [5]="Pet: \"Mag.Atk.Bns.\"+11"
        }
    }, 
    [23]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Mag. Acc.+13 \"Mag.Atk.Bns.\"+13", 
            [2]="Magic burst mdg.+10%", 
            [3]="\"Mag.Atk.Bns.\"+14"
        }
    }
}