-- Generated by the Organizer Library (02/15/16 21:14:59)
return {
    [1]={
        ["log_name"]="fervor ring", 
        ["id"]=11675, 
        ["name"]="fervor ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="glyphic bracers", 
        ["id"]=27004, 
        ["name"]="glyphic bracers", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="sirona's ring", 
        ["id"]=11646, 
        ["name"]="sirona's ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="heka's kalasiris", 
        ["id"]=11867, 
        ["name"]="heka's kalasiris", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="beckoner's horn +1", 
        ["id"]=26769, 
        ["name"]="beckoner's horn +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="deino collar", 
        ["id"]=26018, 
        ["name"]="deino collar", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="domesticator's earring", 
        ["id"]=28505, 
        ["name"]="domes. earring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="orunmila's torque", 
        ["id"]=10394, 
        ["name"]="orunmila's torque", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="consummation torque", 
        ["id"]=26000, 
        ["name"]="consumm. torque", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="yamabuki-no-obi", 
        ["id"]=28443, 
        ["name"]="yamabuki-no-obi", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="eddy necklace", 
        ["id"]=28401, 
        ["name"]="eddy necklace", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="caller's sash", 
        ["id"]=11739, 
        ["name"]="caller's sash", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="gelos earring", 
        ["id"]=27528, 
        ["name"]="gelos earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="convoker's horn", 
        ["id"]=27677, 
        ["name"]="convoker's horn", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="stone gorget", 
        ["id"]=13177, 
        ["name"]="stone gorget", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="apogee pumps", 
        ["id"]=27380, 
        ["name"]="apogee pumps", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="beckoner's pigaches +1", 
        ["id"]=27440, 
        ["name"]="beck. pigaches +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="scintillating cape", 
        ["id"]=26241, 
        ["name"]="scintillating cape", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="nahtirah hat", 
        ["id"]=27775, 
        ["name"]="nahtirah hat", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="pahtli cape", 
        ["id"]=28640, 
        ["name"]="pahtli cape", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+24 \"Mag.Atk.Bns.\"+24", 
            [2]="Mag. crit. hit dmg. +1%", 
            [3]="MND+3", 
            [4]="\"Mag.Atk.Bns.\"+15"
        }
    }, 
    [30]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+9 \"Mag.Atk.Bns.\"+9", 
            [2]="\"Fast Cast\"+7", 
            [3]="Mag. Acc.+4", 
            [4]="\"Mag.Atk.Bns.\"+12"
        }
    }, 
    [31]={
        ["log_name"]="refraction cape", 
        ["id"]=28643, 
        ["name"]="refraction cape", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="glyphic pigaches +1", 
        ["id"]=27357, 
        ["name"]="glyph. pigaches +1", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="oneiros grip", 
        ["id"]=18811, 
        ["name"]="oneiros grip", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="esper earring", 
        ["id"]=11052, 
        ["name"]="esper earring", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="amalric gages", 
        ["id"]=27119, 
        ["name"]="amalric gages", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="beckoner's doublet +1", 
        ["id"]=26927, 
        ["name"]="beck. doublet +1", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="apogee slacks", 
        ["id"]=27204, 
        ["name"]="apogee slacks", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="steelflash earring", 
        ["id"]=28520, 
        ["name"]="steelflash earring", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="seraphicaller", 
        ["id"]=21381, 
        ["name"]="seraphicaller", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="herald's gaiters", 
        ["id"]=15322, 
        ["name"]="herald's gaiters", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="novio earring", 
        ["id"]=14808, 
        ["name"]="novio earring", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="incarnation sash", 
        ["id"]=28418, 
        ["name"]="incarnation sash", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="glyphic doublet +1", 
        ["id"]=26829, 
        ["name"]="glyphic doublet +1", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="kuku stone", 
        ["id"]=28457, 
        ["name"]="kuku stone", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="caller's bracers +2", 
        ["id"]=11118, 
        ["name"]="call. bracers +2", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="evoker's ring", 
        ["id"]=14625, 
        ["name"]="evoker's ring", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="bladeborn earring", 
        ["id"]=28521, 
        ["name"]="bladeborn earring", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="nabu's shalwar", 
        ["id"]=28079, 
        ["name"]="nabu's shalwar", 
        ["count"]=1
    }, 
    [51]={
        ["log_name"]="shomonjijoe +1", 
        ["id"]=26888, 
        ["name"]="shomonjijoe +1", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="strendu ring", 
        ["id"]=11669, 
        ["name"]="strendu ring", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="lucidity sash", 
        ["id"]=28416, 
        ["name"]="lucidity sash", 
        ["count"]=1
    }, 
    [54]={
        ["log_name"]="lamassu mitts +1", 
        ["id"]=27109, 
        ["name"]="lamassu mitts +1", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="gifted earring", 
        ["id"]=11700, 
        ["name"]="gifted earring", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="hagondes pants", 
        ["count"]=1, 
        ["id"]=28196, 
        ["name"]="hagondes pants", 
        ["augments"]={
            [1]="Phys. dmg. taken -3%", 
            [2]="Pet: Mag. Acc +22"
        }
    }, 
    [57]={
        ["log_name"]="marduk's tiara +1", 
        ["id"]=27651, 
        ["name"]="marduk's tiara +1", 
        ["count"]=1
    }, 
    [58]={
        ["log_name"]="speaker's ring", 
        ["id"]=26170, 
        ["name"]="speaker's ring", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="shedir seraweels", 
        ["id"]=10329, 
        ["name"]="shedir seraweels", 
        ["count"]=1
    }, 
    [60]={
        ["log_name"]="asteria mitts +1", 
        ["id"]=27107, 
        ["name"]="asteria mitts +1", 
        ["count"]=1
    }, 
    [61]={
        ["log_name"]="hagondes coat", 
        ["count"]=1, 
        ["id"]=27916, 
        ["name"]="hagondes coat", 
        ["augments"]={
            [1]="Phys. dmg. taken -3%", 
            [2]="Mag. Atk. Bns. +20"
        }
    }, 
    [62]={
        ["log_name"]="empath necklace", 
        ["id"]=27514, 
        ["name"]="empath necklace", 
        ["count"]=1
    }, 
    [63]={
        ["log_name"]="apogee crown +1", 
        ["id"]=26677, 
        ["name"]="apogee crown +1", 
        ["count"]=1
    }, 
    [64]={
        ["log_name"]="bokwus gloves", 
        ["id"]=28059, 
        ["name"]="bokwus gloves", 
        ["count"]=1
    }, 
    [65]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [66]={
        ["log_name"]="beckoner's spats +1", 
        ["id"]=27266, 
        ["name"]="beck. spats +1", 
        ["count"]=1
    }, 
    [67]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [68]={
        ["log_name"]="apogee mitts +1", 
        ["id"]=27029, 
        ["name"]="apogee mitts +1", 
        ["count"]=1
    }, 
    [69]={
        ["log_name"]="hagondes cuffs", 
        ["id"]=28055, 
        ["name"]="hagondes cuffs", 
        ["count"]=1
    }, 
    [70]={
        ["log_name"]="caller's pendant", 
        ["id"]=11619, 
        ["name"]="caller's pendant", 
        ["count"]=1
    }, 
    [71]={
        ["log_name"]="summoner's horn +2", 
        ["id"]=10664, 
        ["name"]="smn. horn +2", 
        ["count"]=1
    }
}