-- Generated by the Organizer Library (03/07/16 17:11:26)
return {
    [1]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="marduk's jubbah +1", 
        ["id"]=27791, 
        ["name"]="marduk's jubbah +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="nahtirah hat", 
        ["id"]=27775, 
        ["name"]="nahtirah hat", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="genbu's shield", 
        ["id"]=12296, 
        ["name"]="genbu's shield", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="phalaina locket", 
        ["id"]=10960, 
        ["name"]="phalaina locket", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="bihu justaucorps +1", 
        ["id"]=26819, 
        ["name"]="bihu jstcorps +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="gendewitha gages", 
        ["id"]=28054, 
        ["name"]="gendewitha gages", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="wivre hairpin", 
        ["id"]=16128, 
        ["name"]="wivre hairpin", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="vertigo ring", 
        ["id"]=10774, 
        ["name"]="vertigo ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="strendu ring", 
        ["id"]=11669, 
        ["name"]="strendu ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="gjallarhorn", 
        ["id"]=18572, 
        ["name"]="gjallarhorn", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="aoidos' matinee", 
        ["id"]=11618, 
        ["name"]="aoidos' matinee", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="heka's kalasiris", 
        ["id"]=11867, 
        ["name"]="heka's kalasiris", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="daurdabla", 
        ["id"]=18571, 
        ["name"]="daurdabla", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="lifestorm earring", 
        ["id"]=28524, 
        ["name"]="lifestorm earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="wind torque", 
        ["id"]=13161, 
        ["name"]="wind torque", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="iaso cuffs", 
        ["id"]=10543, 
        ["name"]="iaso cuffs", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="marduk's shalwar +1", 
        ["id"]=28074, 
        ["name"]="mdk. shalwar +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="paean mitra", 
        ["id"]=10404, 
        ["name"]="paean mitra", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="gifted earring", 
        ["id"]=11700, 
        ["name"]="gifted earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="fili manchettes", 
        ["id"]=27070, 
        ["name"]="fili manchettes", 
        ["count"]=1
    }
}